### ISSUE TITLE
ExtractCoverThumbs

### ISSUE THREAD

**Issue by zsokolowski** [quiris11/ExtractCoverThumbs#4] opened 2016-05-21 07:41 UTC
It just hung, probably due to broken ebook, but still there is no logs. And if process cannot continue it should skip and report broken item, not just hung (0.9.3) I'm open as previously to help.

**Comment by quiris11** [comment] 2016-05-21 07:46
Do you run a compiled executable file (.exe)?

**Comment by zsokolowski** [comment] 2016-05-21 07:48
exactly, Windows version and not console, there should be debug button.

**Comment by zsokolowski** [comment] 2016-05-21 07:51
btw I've choosen an option, process less than 7 days

**Comment by quiris11** [comment] 2016-05-21 07:52
If so the app is probably (99.99%) blocked by your antivirus application. Try to disable your antivirus or run extracted ZIP file with installed Python 2.7.x (double click on gui.pywfile).

**Comment by zsokolowski** [comment] 2016-05-21 07:54
For sure not, when I disable (process less than day option) it processes correctly books till it stops.

**Comment by quiris11** [comment] 2016-05-21 07:57
Can you provide a log (a content of a message window)?

**Comment by zsokolowski** [comment] 2016-05-21 08:02
- Updating book pages CSV file...
- Żyj wystarczająco dobrze_S6TXRO7L67AWI6KUU4T4RWVD5DPSBJPV.azw3: skipped (cover present or overwriting not forced).
  START of generating book page numbers (APNX files)...
- Generating APNX file for "228 Italian Recipes_ Cook The Best Italian Food With These Amazing Easy Italian Recipes Like Italian Pasta, Italian Chicken, Italian Soups, Italian Sau_B00AG3T0Z2.azw3"
  - Using 226 pages defined in extract_cover_thumbs-book-pages.csv
- Generating APNX file for "Creme de la Kreml.azw_QPNDXWVDSDESZM2QXB42RWTR2YGU7SUB.azw"

how to produce log file?

**Comment by quiris11** [comment] 2016-05-21 08:07
The message window contains a log. Debugging is not possible. The posted log shows no suspects, so I strongly advise disable antivirus or running application straight from a source as described above.

**Comment by zsokolowski** [comment] 2016-05-21 08:08
whith whole respect I would recommend to add sumary line to log to ensure that process finished

**Comment by zsokolowski** [comment] 2016-05-21 08:10
and with 7 days, log window is just empty, and books were uploaded yesterday, I would implement exceptions in other way, changing option in app do not change antivir action

**Comment by quiris11** [comment] 2016-05-21 08:34
There is a summary after completing completing task. As I said earlier such strange behavior described by you is for sure caused by antivirus. Check comments on my blog (in Polish): http://blog.blaut.biz for similar reports.

**Comment by zsokolowski** [comment] 2016-05-21 09:01
so if you can't see summary in log which I copied above it should be clear that something went wrong, don't you think?

**Comment by quiris11** [comment] 2016-05-22 08:26
ExtractCoverThumbs is a simple script written in my free time which wasn't planed to be compiled as exe. It doesn't have an advanced logic to detection antivirus access to file blocks. I will eventually look for the problem, but I can't promise that it will be fixed.

**Closed as completed** 2016-07-18 05:56 UTC
